# Generated by Django 4.1.1 on 2022-10-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("usable", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=1028)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ov", "Open VPN"),
                            ("lv", "L2TP"),
                            ("ss", "ShadowSocks"),
                            ("cc", "Cisco Connect"),
                        ],
                        max_length=2,
                    ),
                ),
                ("host", models.CharField(max_length=128)),
                ("port", models.IntegerField()),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ciscoConfig",
            fields=[
                (
                    "configuration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vpn.configuration",
                    ),
                ),
                ("username", models.CharField(max_length=128)),
            ],
            bases=("vpn.configuration",),
        ),
        migrations.CreateModel(
            name="l2tpConfig",
            fields=[
                (
                    "configuration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vpn.configuration",
                    ),
                ),
                ("username", models.CharField(max_length=128)),
            ],
            bases=("vpn.configuration",),
        ),
        migrations.CreateModel(
            name="OpenVpnConfig",
            fields=[
                (
                    "configuration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vpn.configuration",
                    ),
                ),
                ("username", models.CharField(max_length=128)),
            ],
            bases=("vpn.configuration",),
        ),
        migrations.CreateModel(
            name="ShadowSocksConfig",
            fields=[
                (
                    "configuration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vpn.configuration",
                    ),
                ),
                (
                    "encryption",
                    models.CharField(
                        choices=[
                            ("chacha20poly", "chacha20-ietf-poly1305"),
                            ("256gcm", "aes-256-gcm"),
                            ("256ctr", "aes-256-ctr"),
                            ("256cfb", "aes-256-cfb"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
            bases=("vpn.configuration",),
        ),
    ]
