# Generated by Django 4.1.1 on 2022-10-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="type",
        ),
    ]
