# Generated by Django 4.1.1 on 2022-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0002_remove_configuration_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="failed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="configuration",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="configuration",
            name="success",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="description",
            field=models.CharField(blank=True, max_length=1028),
        ),
    ]
