# Generated by Django 4.1.1 on 2022-10-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0003_configuration_failed_configuration_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="enable",
            field=models.BooleanField(default=True),
        ),
    ]
