# Generated by Django 4.1.1 on 2022-10-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0004_configuration_enable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
