# Generated by Django 4.1.1 on 2022-10-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0006_remove_configuration_usable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="password",
        ),
        migrations.AddField(
            model_name="ciscoconfig",
            name="password",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="l2tpconfig",
            name="password",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="openvpnconfig",
            name="password",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shadowsocksconfig",
            name="password",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
