# Generated by Django 4.1.1 on 2022-11-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0007_remove_configuration_password_ciscoconfig_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openvpnconfig",
            name="no_deflate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="openvpnconfig",
            name="no_dtls",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="openvpnconfig",
            name="passtos",
            field=models.BooleanField(default=False),
        ),
    ]
