# Generated by Django 4.1.1 on 2022-11-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0008_openvpnconfig_no_deflate_openvpnconfig_no_dtls_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openvpnconfig",
            name="no_deflate",
        ),
        migrations.RemoveField(
            model_name="openvpnconfig",
            name="no_dtls",
        ),
        migrations.RemoveField(
            model_name="openvpnconfig",
            name="passtos",
        ),
        migrations.AddField(
            model_name="ciscoconfig",
            name="no_deflate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ciscoconfig",
            name="no_dtls",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ciscoconfig",
            name="passtos",
            field=models.BooleanField(default=False),
        ),
    ]
