# Generated by Django 4.1.1 on 2022-11-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0011_alter_ciscoconfig_deflate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenconnectConfig",
            fields=[
                (
                    "configuration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vpn.configuration",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("anyconnect", "Cisco (AnyConnect)"),
                            ("nc", "Juniper Network Connect"),
                            ("gp", "Palo Alto Networks (PAN) GlobalProtect VPN"),
                            ("pulse", "Junos Pulse VPN"),
                            ("f5", "F5 Big-IP VPN"),
                            ("fortinet", "Fortinet Fortigate VPN"),
                            ("array", "Array Networks SSL VPN"),
                        ],
                        default="anyconnect",
                        max_length=128,
                    ),
                ),
                ("username", models.CharField(max_length=128)),
                ("password", models.CharField(max_length=128)),
                (
                    "no_dtls",
                    models.BooleanField(
                        default=False, help_text="Disable DTLS and ESP"
                    ),
                ),
                (
                    "passtos",
                    models.BooleanField(
                        default=False,
                        help_text="Copy TOS / TCLASS of payload packet into DTLS and ESP packets. This is not set by default because it may leak information about the payload (for example, by differentiating voice/video traffic).",
                    ),
                ),
                (
                    "no_deflate",
                    models.BooleanField(
                        default=False, help_text="Disable all compression."
                    ),
                ),
                (
                    "deflate",
                    models.BooleanField(
                        default=False,
                        help_text="Enable all compression, including stateful modes. By default, only stateless compression algorithms are enabled.",
                    ),
                ),
                (
                    "no_http_keepalive",
                    models.BooleanField(
                        default=False,
                        help_text="Version 8.2.2.5 of the Cisco ASA software has a bug where it will forget the client’s SSL certificate when HTTP connections are being re-used for multiple requests. So far, this has only been seen on the initial connection, where the server gives an HTTP/1.0 redirect response with an explicit Connection: Keep-Alive directive. OpenConnect as of v2.22 has an unconditional workaround for this, which is never to obey that directive after an HTTP/1.0 response.",
                    ),
                ),
            ],
            bases=("vpn.configuration",),
        ),
        migrations.DeleteModel(
            name="ciscoConfig",
        ),
    ]
