# Generated by Django 4.1.1 on 2022-11-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0012_openconnectconfig_delete_ciscoconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="V2rayConfig",
            fields=[
                (
                    "configuration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vpn.configuration",
                    ),
                ),
                ("v", models.CharField(default="2", max_length=8)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("vmess", "VMESS"), ("vless", "VLESS")], max_length=8
                    ),
                ),
                ("uid", models.CharField(blank=True, max_length=64)),
                ("alter_id", models.CharField(blank=True, max_length=64)),
                (
                    "tls",
                    models.CharField(
                        blank=True,
                        choices=[("tls", "TLS"), ("off", "OFF")],
                        max_length=8,
                    ),
                ),
                ("tls_allow_insecure", models.BooleanField(default=False)),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        choices=[("tpc", "TCP"), ("ws", "WebSocket")],
                        max_length=8,
                    ),
                ),
                ("ws_path", models.CharField(blank=True, max_length=512)),
                ("ws_host", models.CharField(blank=True, max_length=256)),
                ("config_url", models.CharField(blank=True, max_length=2048)),
                ("config_json", models.CharField(blank=True, max_length=4098)),
            ],
            bases=("vpn.configuration",),
        ),
    ]
