# Generated by Django 4.1.1 on 2022-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0013_v2rayconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="V2rayUrlConfig",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vpn.v2rayconfig",),
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="host",
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="port",
        ),
        migrations.AddField(
            model_name="openconnectconfig",
            name="host",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="openconnectconfig",
            name="port",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shadowsocksconfig",
            name="host",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shadowsocksconfig",
            name="port",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="v2rayconfig",
            name="host",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="v2rayconfig",
            name="port",
            field=models.IntegerField(null=True),
        ),
    ]
