# Generated by Django 4.1.1 on 2022-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0015_configuration_last_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v2rayconfig",
            name="network",
            field=models.CharField(
                blank=True, choices=[("tcp", "TCP"), ("ws", "WebSocket")], max_length=8
            ),
        ),
    ]
