# Generated by Django 4.1.1 on 2022-11-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0016_alter_v2rayconfig_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="v2rayconfig",
            name="security",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="v2rayconfig",
            name="alter_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="v2rayconfig",
            name="ws_host",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="v2rayconfig",
            name="ws_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
