# Generated by Django 4.1.1 on 2022-11-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0017_v2rayconfig_security_alter_v2rayconfig_alter_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v2rayconfig",
            name="tls",
            field=models.CharField(
                blank=True, choices=[("tls", "TLS"), ("none", "None")], max_length=8
            ),
        ),
    ]
