# Generated by Django 4.1.1 on 2022-11-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0018_alter_v2rayconfig_tls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="security",
        ),
    ]
