# Generated by Django 4.1.1 on 2022-12-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0019_remove_v2rayconfig_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
