# Generated by Django 4.1.1 on 2022-12-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0020_alter_configuration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
