# Generated by Django 4.1.1 on 2022-12-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0022_alter_configuration_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="config_json",
        ),
        migrations.AddField(
            model_name="v2rayconfig",
            name="ws_sni",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="v2rayconfig",
            name="protocol",
            field=models.CharField(
                choices=[("vmess", "VMESS"), ("vless", "VLESS"), ("trojan", "TROJAN")],
                max_length=8,
            ),
        ),
    ]
