# Generated by Django 4.1.1 on 2022-12-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0023_remove_v2rayconfig_config_json_v2rayconfig_ws_sni_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="failed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="success",
            field=models.IntegerField(default=0),
        ),
    ]
