# Generated by Django 4.1.1 on 2023-01-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0024_alter_configuration_failed_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="V2rayUrlConfig",
        ),
        migrations.RenameField(
            model_name="openconnectconfig",
            old_name="host",
            new_name="hostname",
        ),
        migrations.RenameField(
            model_name="shadowsocksconfig",
            old_name="host",
            new_name="hostname",
        ),
        migrations.RenameField(
            model_name="v2rayconfig",
            old_name="host",
            new_name="hostname",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="alter_id",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="network",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="port",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="tls",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="tls_allow_insecure",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="v",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="ws_host",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="ws_path",
        ),
        migrations.RemoveField(
            model_name="v2rayconfig",
            name="ws_sni",
        ),
    ]
