# Generated by Django 4.1.1 on 2023-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0025_delete_v2rayurlconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v2rayconfig",
            name="config_url",
            field=models.CharField(blank=True, max_length=8192),
        ),
    ]
