# Generated by Django 4.1.1 on 2023-01-25 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0026_alter_v2rayconfig_config_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="openvpnconfig",
            name="ovpn_file",
            field=models.FileField(
                default=None,
                upload_to="ovpn/",
                validators=[django.core.validators.FileExtensionValidator(["ovpn"])],
            ),
        ),
        migrations.AlterField(
            model_name="v2rayconfig",
            name="config_url",
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="v2rayconfig",
            name="hostname",
            field=models.CharField(max_length=128),
        ),
    ]
