# Generated by Django 4.1.1 on 2023-01-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0027_openvpnconfig_ovpn_file_alter_v2rayconfig_config_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
