# Generated by Django 4.1.1 on 2023-02-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
        ("vpn", "0028_alter_configuration_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="subscription",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subscriptionconfig",
            ),
        ),
    ]
