# Generated by Django 4.1.1 on 2022-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotspot", "0004_remove_status_activeprofile_status_active_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dhcp_ip_from",
            field=models.CharField(default="192.168.10.10", max_length=16),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dhcp_ip_to",
            field=models.CharField(default="192.168.10.30", max_length=16),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ip",
            field=models.CharField(default="192.168.10.1", max_length=16),
        ),
        migrations.AlterField(
            model_name="profile",
            name="netmask",
            field=models.CharField(default="255.255.255.0", max_length=20),
        ),
    ]
