# Generated by Django 4.1.1 on 2022-10-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hotspot",
            "0005_alter_profile_dhcp_ip_from_alter_profile_dhcp_ip_to_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.CharField(blank=True, max_length=1028),
        ),
    ]
