# Generated by Django 4.1.1 on 2022-10-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotspot", "0006_alter_profile_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
    ]
