# Generated by Django 4.1.1 on 2022-11-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotspot", "0009_alter_profile_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dns",
            field=models.CharField(
                default="1.1.1.1,8.8.8.8,208.67.222.222", max_length=128
            ),
        ),
    ]
