# Generated by Django 4.1.1 on 2022-11-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotspot", "0010_profile_dns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dns",
            field=models.CharField(
                blank=True, default="1.1.1.1,8.8.8.8,208.67.222.222", max_length=128
            ),
        ),
    ]
