# Generated by Django 4.1.1 on 2022-11-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotspot", "0011_alter_profile_dns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="dns",
        ),
    ]
