# Generated by Django 4.1.1 on 2022-11-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dnsMode",
                    models.CharField(
                        choices=[
                            ("_1", "Do Nothing"),
                            ("_2", "Handle in system"),
                            ("_3", "Handle in hotspot"),
                            ("_4", "Handle with socks (only for v2ray)"),
                        ],
                        default="_2",
                        max_length=8,
                    ),
                ),
                (
                    "dns",
                    models.CharField(
                        blank=True,
                        default="1.1.1.1,8.8.8.8,208.67.222.222",
                        max_length=128,
                    ),
                ),
            ],
        ),
    ]
