# Generated by Django 4.1.1 on 2022-11-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setting",
            old_name="dnsMode",
            new_name="dns_Mode",
        ),
    ]
