# Generated by Django 4.1.1 on 2022-12-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0003_dhcpserverconfig_hotspotconfig_lanconfig_wlanconfig"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Setting",
            new_name="General",
        ),
    ]
