# Generated by Django 4.1.1 on 2022-12-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0004_rename_setting_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpserverconfig",
            name="dhcp_module",
            field=models.CharField(
                choices=[
                    ("dnsmasq", "dnsmasq"),
                    ("isc-dhcp-server", "isc-dhcp-server"),
                ],
                default="isc-dhcp-server",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="dns_Mode",
            field=models.CharField(
                choices=[
                    ("1", "Do Nothing"),
                    ("2", "Handle in system"),
                    ("3", "Handle with socks (only for v2ray)"),
                ],
                default="2",
                max_length=8,
            ),
        ),
    ]
