# Generated by Django 4.1.1 on 2022-12-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0005_dhcpserverconfig_dhcp_module_alter_general_dns_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="log",
            field=models.BooleanField(default=False),
        ),
    ]
