# Generated by Django 4.1.1 on 2022-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0006_general_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotspotconfig",
            name="mac_address_filter_list",
            field=models.CharField(blank=True, max_length=4098),
        ),
        migrations.AddField(
            model_name="hotspotconfig",
            name="mac_address_filter_mode",
            field=models.CharField(
                choices=[
                    ("disable", "Disable"),
                    ("block", "Block"),
                    ("accept", "Allow"),
                ],
                default="disable",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="hotspotconfig",
            name="wpa_passphrase",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
