# Generated by Django 4.1.1 on 2022-12-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0007_hotspotconfig_mac_address_filter_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotspotconfig",
            name="country_code",
            field=models.CharField(default="IR", max_length=8),
        ),
    ]
