# Generated by Django 4.1.1 on 2022-12-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0008_hotspotconfig_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="check_vpn_curl_domain_list",
            field=models.CharField(
                blank=True,
                default="https://api.ipify.org?format=json\n",
                max_length=4098,
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="check_vpn_curl_retry",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="general",
            name="check_vpn_curl_timeout",
            field=models.IntegerField(default=3),
        ),
    ]
