# Generated by Django 4.1.1 on 2022-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0010_remove_general_check_vpn_curl_domain_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="v2ray_mode",
            field=models.CharField(
                choices=[
                    ("badvpn-tun2socks", "badvpn-tun2socks"),
                    ("go-tun2socks", "go-tun2socks"),
                ],
                default="badvpn-tun2socks",
                max_length=64,
            ),
        ),
    ]
