# Generated by Django 4.1.1 on 2022-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0011_general_v2ray_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="v2ray_mode",
            field=models.CharField(
                choices=[
                    ("badvpn-tun2socks", "badvpn-tun2socks"),
                    ("go-tun2socks", "go-tun2socks"),
                    ("tun2socks", "tun2socks"),
                ],
                default="badvpn-tun2socks",
                max_length=64,
            ),
        ),
    ]
