# Generated by Django 4.1.1 on 2022-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0012_alter_general_v2ray_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="check_vpn_curl_timeout",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="general",
            name="check_vpn_list_method",
            field=models.CharField(
                choices=[
                    ("once", "Once from all list successful"),
                    ("all", "All from list successful"),
                    ("random", "Once randomly successful from list"),
                ],
                default="once",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="v2ray_mode",
            field=models.CharField(
                choices=[
                    ("badvpn-tun2socks", "badvpn-tun2socks"),
                    ("go-tun2socks", "go-tun2socks"),
                    ("tun2socks", "tun2socks"),
                ],
                default="tun2socks",
                max_length=64,
            ),
        ),
    ]
