# Generated by Django 4.1.1 on 2022-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0013_alter_general_check_vpn_curl_timeout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="dns",
            field=models.CharField(
                blank=True, default="1.1.1.1\n8.8.8.8\n208.67.222.222", max_length=128
            ),
        ),
    ]
