# Generated by Django 4.1.1 on 2022-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0014_alter_general_dns"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="vpn_smart_mode",
            field=models.CharField(
                choices=[
                    ("success_chance", "Success Chance"),
                    ("priority", "Priority"),
                    ("circular", "Circular"),
                ],
                default="success_chance",
                max_length=64,
            ),
        ),
    ]
