# Generated by Django 4.1.1 on 2022-12-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0015_general_vpn_smart_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="check_vpn_curl_retry",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="general",
            name="check_vpn_curl_timeout",
            field=models.IntegerField(default=8),
        ),
    ]
