# Generated by Django 4.1.1 on 2022-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0016_alter_general_check_vpn_curl_retry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dhcpserverconfig",
            name="dhcp_module",
            field=models.CharField(
                choices=[
                    ("dnsmasq", "dnsmasq"),
                    ("isc-dhcp-server", "isc-dhcp-server"),
                ],
                default="dnsmasq",
                max_length=32,
            ),
        ),
    ]
