# Generated by Django 4.1.1 on 2022-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0018_rename_ssid_wlanconfig_ssid1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="check_vpn_curl_retry",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="general",
            name="check_vpn_curl_timeout",
            field=models.IntegerField(default=9),
        ),
    ]
