# Generated by Django 4.1.1 on 2022-12-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "setting",
            "0021_general_default_gateway_general_default_gateway_mode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lanconfig",
            name="dhcp_set_default_gateway",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="wlanconfig",
            name="dhcp_set_default_gateway",
            field=models.BooleanField(default=True),
        ),
    ]
