# Generated by Django 4.1.1 on 2023-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0025_dhcpserverconfig_enable_hotspotconfig_enable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="check_vpn_list_method",
            field=models.CharField(
                choices=[
                    ("one", "One from one of the list successful"),
                    ("two", "One from two of the list successful"),
                    ("three", "One from three of the list successful"),
                    ("all", "One from all of the list successful"),
                    ("strict", "All from all of the list successful"),
                ],
                default="three",
                max_length=64,
            ),
        ),
    ]
