# Generated by Django 4.2.5 on 2023-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0026_alter_general_check_vpn_list_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="number_of_try_for_each_vpn",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="general",
            name="timeout_of_try_for_each_vpn",
            field=models.IntegerField(default=20),
        ),
    ]
