# Generated by Django 4.1.1 on 2023-02-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resync", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="VitaminConfig",
            fields=[
                (
                    "subscriptionconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="subscription.subscriptionconfig",
                    ),
                ),
                (
                    "main_url",
                    models.CharField(default="https://v5gnet.shop", max_length=128),
                ),
                (
                    "serverlist_json",
                    models.CharField(
                        help_text="Please login to your account next goto json page e.g. (https://v5gnet.shop/serverslistjson) and copy content here.",
                        max_length=131072,
                    ),
                ),
                ("username", models.CharField(max_length=128)),
                ("password", models.CharField(max_length=128)),
                ("v2ray_subscription_url", models.CharField(max_length=128)),
                ("openvpn", models.BooleanField(default=True)),
                ("anyconnect", models.BooleanField(default=True)),
                ("v2ray", models.BooleanField(default=True)),
            ],
            bases=("subscription.subscriptionconfig",),
        ),
    ]
