# Generated by Django 4.1.1 on 2022-11-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0013_v2rayconfig"),
        ("hotspot", "0009_alter_profile_channel"),
        ("action", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicestatus",
            name="selected_profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_prof",
                to="hotspot.profile",
            ),
        ),
        migrations.AddField(
            model_name="servicestatus",
            name="selected_vpn",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_vpn",
                to="vpn.configuration",
            ),
        ),
        migrations.AlterField(
            model_name="servicestatus",
            name="active_profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_prof",
                to="hotspot.profile",
            ),
        ),
        migrations.AlterField(
            model_name="servicestatus",
            name="active_vpn",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_vpn",
                to="vpn.configuration",
            ),
        ),
    ]
