# Generated by Django 4.1.1 on 2022-11-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0002_servicestatus_selected_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicestatus",
            name="active_profile",
        ),
        migrations.RemoveField(
            model_name="servicestatus",
            name="selected_profile",
        ),
    ]
