# Generated by Django 4.1.1 on 2022-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0003_remove_servicestatus_active_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicestatus",
            name="apply",
            field=models.BooleanField(default=False),
        ),
    ]
